#!/bin/bash
set -e
cd "$(dirname "$0")"

git pull origin main --rebase 2>/dev/null || true
git push origin main

echo ""
echo "✅ Push完了！"
echo ""
echo "======================================="
echo "  kyuryo-lab 自動化セットアップ完了"
echo "======================================="
echo ""
echo "【今すぐできること】"
echo ""
echo "① アフィリエイトクリック計測（本番反映済み）"
echo "   GA4 > リアルタイム > イベント で"
echo "   affiliate_click イベントが確認できます"
echo ""
echo "② 記事を今すぐ1件生成:"
echo "   node scripts/generate-article.mjs"
echo ""
echo "③ GSC分析（APIなしでもモックデータで動作確認可）:"
echo "   node scripts/analyze-and-improve.mjs --report-only"
echo ""
echo "【cron設定（Mac miniで実行）】"
echo "   crontab -e で以下を追加:"
echo ""
echo "   # 週2回 記事自動生成（月・木 朝8時）"
echo "   0 8 * * 1,4 cd ~/Downloads/kyuryo-lab && bash scripts/run-pipeline.sh >> scripts/pipeline.log 2>&1"
echo ""
echo "   # 週1回 GSC分析→改善（日曜 朝9時）"  
echo "   0 9 * * 0 cd ~/Downloads/kyuryo-lab && node scripts/analyze-and-improve.mjs >> scripts/analysis.log 2>&1"
echo ""
echo "【GSC API設定】"
echo "   scripts/SETUP.md を参照してください"
echo ""
echo "======================================="
